spring:
  data:
    mongodb:
      uri: mongodb+srv://mohitkumawat12345613:Mohit123mohit.@cluster0.thohe1h.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
#      username: mohit
#      password: 123

server:
  port: 8081
  servlet:
    context-path: /journal

